# Generated by Django 5.0.3 on 2024-05-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('priority', models.IntegerField(choices=[(1, 'urgent'), (2, 'normal'), (3, 'not important')])),
            ],
        ),
    ]
