# Generated by Django 5.0.3 on 2024-05-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='genres',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='music',
            name='singer',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='music',
            name='year',
            field=models.IntegerField(),
        ),
    ]
