# Generated by Django 5.0.3 on 2024-05-09 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_music_genres_alter_music_singer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('born', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='music',
            name='genres',
        ),
        migrations.AlterField(
            model_name='music',
            name='singer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='music.singer'),
        ),
        migrations.AddField(
            model_name='music',
            name='genres',
            field=models.ManyToManyField(null=True, to='music.genres'),
        ),
    ]
